### ISSUE TITLE
UBUNTU =(

### ISSUE THREAD

**Issue by vladimirss7** [milksense/qrmosru-brute#2]
npm i

> install
> lerna bootstrap

lerna notice cli v4.0.0
lerna info Bootstrapping 1 package
lerna info Symlinking packages and binaries
lerna success Bootstrapped 1 package

up to date, audited 621 packages in 3s

67 packages are looking for funding
  run `npm fund` for details

found 0 vulnerabilities

-------------------------------------------------------------------------
npm start

> start
> lerna run --scope app start

lerna notice cli v4.0.0
lerna notice filter including "app"
lerna info filter [ 'app' ]
lerna success run No packages found with the lifecycle script 'star

**Comment by milksense** [comment]
Run 
```
npm start
``` from root directory of project

**Comment by vladimirss7** [comment]
nope (  same in Kali 

~/Downloads/qrmosru-brute$ npm start

> start
> lerna run --scope app start

lerna notice cli v4.0.0
lerna notice filter including "app"
lerna info filter [ 'app' ]
lerna info Executing command in 1 package: "npm run start"
lerna info run Ran npm script 'start' in 'app' in 2.7s:

> app@1.0.0 start
> tsc&& node ./dist/index.js

lerna success run Ran npm script 'start' in 1 package in 2.7s:
lerna success - app

**Comment by milksense** [comment]
After running all those steps, u'll see the output in `qrmosru-brute/packages/app/dist` directory

**Comment by vladimirss7** [comment]
final countdown =) 
sudo npm start

> app@1.0.0 start
> tsc&& node ./dist/index.js

(node:40424) UnhandledPromiseRejectionWarning: Error: Could not find expected browser (chrome) locally. Run `npm install` to download the correct Chromium revision (901912).
    at ChromeLauncher.launch (/home/*****/Downloads/qrmosru-brute/packages/app/node_modules/puppeteer/lib/cjs/puppeteer/node/Launcher.js:88:27)
(node:40424) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:40424) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by milksense** [comment]
Run npm install to download the correct Chromium revision (901912). 😄
