### ISSUE TITLE
parses one certificate

### ISSUE THREAD

**Issue by Pushkin31** [milksense/qrmosru-brute#3]
hello. doesn't work anymore?
parses only 1 certificate, it's valid, but 1986 - it doesn't suit me)
how to parse another one?

**Comment by milksense** [comment]
Fixed in [last](https://github.com/milksense/qrmosru-brute/tree/acb0adf9bc1b4e700645aca34fbe5ef330fbb831) version.
Wish you Merry Christmas and happy new year 🤶
